In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
import sklearn
from sklearn.cluster import DBSCAN

In [87]:
df=pd.read_excel("output.xlsx")

In [88]:
df.head()

,InvoiceNo,StockCode,UnitPrice,Quantity,lower,Description,InvoiceDate,CustomerID,Country
0,536365,0.169726,7.65,2,set 7 babushka nesting boxes,SET 7 BABUSHKA NESTING BOXES,2010-12-01 08:26:00,1.000000,United Kingdom
1,536365,0.156121,4.25,6,glass star frosted t-light holder,GLASS STAR FROSTED T-LIGHT HOLDER,2010-12-01 08:26:00,1.000000,United Kingdom
2,536366,0.168142,1.85,6,hand warmer union jack,HAND WARMER UNION JACK,2010-12-01 08:28:00,1.000000,United Kingdom
3,536366,0.168129,1.85,6,hand warmer red polka dot,HAND WARMER RED POLKA DOT,2010-12-01 08:28:00,1.000000,United Kingdom
4,536367,0.169633,2.10,6,poppy's playhouse bedroom,POPPY'S PLAYHOUSE BEDROOM,2010-12-01 08:34:00,0.088096,United Kingdom

In [108]:
data=df.iloc[:,1:4]

In [109]:
data

    StockCode  UnitPrice  Quantity
0    0.169726       7.65         2
1    0.156121       4.25         6
2    0.168142       1.85         6
3    0.168129       1.85         6
4    0.169633       2.10         6
5    0.169673       2.10         6
6    0.169686       3.75         8
7    0.163842       1.65         6
8    0.168009       4.95         3
9    0.167996       9.95         2
10   0.156441       5.95         3
11   0.156454       5.95         3
12   0.156747       7.95         4
13   0.172495       4.25         6
14   0.171869       4.95         3
15   0.171856       4.95         3
16   0.171883       4.95         3
17   0.156468       5.95         3
18   0.169407       3.75        24
19   0.169393       3.75        24
20   0.169380       3.75        12
21   0.156042       0.85        12
22   0.158158       0.65        24
23   0.000000       0.85        48
24   0.156933       1.25        24
25   0.146870       2.95        18
26   0.164055       2.95        24
27   0.168089       1.95        24
28   0.168488       1.95        24
29   0.168115       1.95        24
30   0.168515       0.85        20
31   0.156135       1.65        24
32   0.171696       2.95        24
33   0.158558       3.75        12
34   0.166904       0.42        24
35   0.166957       0.42        24
36   0.166265       0.65        36
37   0.135049      18.00         3
38   0.160860       2.55        80
39   0.168129       1.85         6
40   0.168142       1.85         6
41   1.000000       2.55         6
42   0.812702       3.39         6
43   0.990455       2.75         8
44   0.985437       3.39         6
45   0.985437       3.39         6
46   0.996752       1.69        32
47   0.997950       4.25         6
48   1.000000       2.55         6
49   0.508313       7.95         4

In [110]:
%%time
model=DBSCAN(eps=0.8).fit(data)

Wall time: 1.99 ms

In [111]:
print(model)

DBSCAN(algorithm='auto', eps=0.8, leaf_size=30, metric='euclidean',
    metric_params=None, min_samples=5, n_jobs=None, p=None)

In [112]:
outliers_df=pd.DataFrame(data)
from collections import Counter
print (Counter(model.labels_))

Counter({-1: 37, 0: 7, 1: 6})

In [113]:
print(outliers_df[model.labels_==0])

    StockCode  UnitPrice  Quantity
2    0.168142       1.85         6
3    0.168129       1.85         6
4    0.169633       2.10         6
5    0.169673       2.10         6
7    0.163842       1.65         6
39   0.168129       1.85         6
40   0.168142       1.85         6

In [116]:
outliers_df[model.labels_==0].to_excel("cluster1.xlsx")

In [117]:
outliers_df[model.labels_==-1].to_excel("cluster2.xlsx")

In [118]:
outliers_df[model.labels_==1].to_excel("cluster3.xlsx")